apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}-configmap
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
data:
  configuration.yaml: |-
{{ .Values.zigbee2mqtt.config | toYaml | trimSuffix "\n" | indent 4 }}
