apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pi-hole.fullname" . }}-configmap
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
data:
  TZ: "{{ .Values.pihole.env.TZ }}"
  #FTLCONF_LOCAL_IPV4: "{{ .Values.pihole.env.FTLCONF_LOCAL_IPV4 }}"
  #PIHOLE_DOCKER_TAG: "{{ .Values.image.tag | default .Chart.AppVersion }}"

  # extra environment
  {{- range $key, $value := .Values.pihole.extraEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
