apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-dns
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  {{- with .Values.service.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
{{- if .Values.service.dns.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.dns.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.dns.ipFamilies }}
  ipFamilies: {{ toYaml .Values.service.dns.ipFamilies | nindent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.dns.ports.dnstcp }}
      targetPort: dnstcp
      protocol: TCP
      name: dnstcp
    - port: {{ .Values.service.dns.ports.dnsudp }}
      targetPort: dnsudp
      protocol: UDP
      name: dnsudp
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}
