{{- $extTrafficPolicy := "" }}
{{- $svcs := list "LoadBalancer" "NodePort" }}
{{- if has .Values.service.dns.type $svcs }}
{{- $extTrafficPolicy = "Local" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-dns
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  {{- with .Values.service.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
{{- with .Values.service.dns.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
{{- end }}
{{- with .Values.service.dns.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
{{- end }}
  externalTrafficPolicy: {{ $extTrafficPolicy }}
  ports:
    - port: {{ .Values.service.dns.ports.dnstcp }}
      targetPort: dnstcp
      protocol: TCP
      name: dnstcp
    - port: {{ .Values.service.dns.ports.dnsudp }}
      targetPort: dnsudp
      protocol: UDP
      name: dnsudp
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}
