{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "wireguard.fullname" . }}-external-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.wireguard.secret.name }}
    template:
      engineVersion: v2
      data:
        wgc0.conf: |
          [Interface]
          Address = {{ "{{" }} .address {{ "}}" }}
          PrivateKey = {{ "{{" }} .privateKey {{ "}}" }}
          {{ range $i, $peer := .Values.externalSecret.remoteRefs.peers }}
          [Peer]
          PublicKey = {{ "{{" }} .publicKey{{ $i }} {{ "}}" }}
          PresharedKey = {{ "{{" }} .presharedKey{{ $i }} {{ "}}" }}
          AllowedIPs = {{ "{{" }} .allowedIPs{{ $i }} {{ "}}" }}
          Endpoint = {{ "{{" }} .endpoint{{ $i }} {{ "}}" }}
          PersistentKeepalive = {{ "{{" }} .keepalive{{ $i }} {{ "}}" }}
          {{ end }}
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  data:
    - secretKey: address
      remoteRef:
        {{- with .Values.externalSecret.remoteRefs.interface.address.key }}
        key: {{ . }}
        {{- end }}
        {{- with .Values.externalSecret.remoteRefs.interface.address.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: privateKey
      remoteRef:
        {{- with .Values.externalSecret.remoteRefs.interface.privateKey.key }}
        key: {{ . }}
        {{- end }}
        {{- with .Values.externalSecret.remoteRefs.interface.privateKey.property }}
        property: {{ . }}
        {{- end }}
    {{ range $i, $peer := .Values.externalSecret.remoteRefs.peers -}}
    - secretKey: publicKey{{ $i }}
      remoteRef:
        {{- with $peer.publicKey.key }}
        key: {{ . }}
        {{- end }}
        {{- with $peer.publicKey.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: presharedKey{{ $i }}
      remoteRef:
        {{- with $peer.presharedKey.key }}
        key: {{ . }}
        {{- end }}
        {{- with $peer.presharedKey.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: allowedIPs{{ $i }}
      remoteRef:
        {{- with $peer.allowedIPs.key }}
        key: {{ . }}
        {{- end }}
        {{- with $peer.allowedIPs.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: endpoint{{ $i }}
      remoteRef:
        {{- with $peer.endpoint.key }}
        key: {{ . }}
        {{- end }}
        {{- with $peer.endpoint.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: keepalive{{ $i }}
      remoteRef:
        {{- with $peer.keepalive.key }}
        key: {{ . }}
        {{- end }}
        {{- with $peer.keepalive.property }}
        property: {{ . }}
        {{- end }}
    {{ end }}
{{- end }}
