{{- if .Values.externalSecrets.enabled }}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ha-proxy.fullname" . }}
  labels:
    {{- include "ha-proxy.labels" . | nindent 4 }}
spec:
  refreshPolicy: {{ .Values.externalSecrets.refreshPolicy }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ required "token.secretName is required" .Values.token.secretName }}
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
