apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: websocket
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
