apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- $fname := "" }}
    {{- if .Values.ha.includeDefaultConfig }}
    default_config:
    {{- end }}
    {{- range .Values.ha.extraConfigFiles }}
    {{- if .key }}
    {{- $fname = printf "%s.yaml" .key }}
    {{- else }}
    {{- $fname = .filename }}
    {{- end }}
    {{- if .key }}
    {{ .key }}: !include {{ $fname }}
    {{- end }}
    {{- end }}
    {{- if .Values.ha.config }}
    {{- .Values.ha.config | nindent 4 }}
    {{- end }}
  {{- range .Values.ha.extraConfigFiles }}
  {{- if .key }}
  {{- $fname = printf "%s.yaml" .key }}
  {{- else }}
  {{- $fname = .filename }}
  {{- end }}
  {{ $fname }}: |
    {{- if .template }}
    {{- tpl .content $ | nindent 4 }}
    {{- else }}
    {{- .content | nindent 4 }}
    {{- end }}
  {{- end }}
