apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.ha.configFiles }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
