ha:
  config: |
    test: content
  extraConfigFiles:
    - key: customize
      filename: customize.yaml
      content: |
        light.living_room_lamp:
          friendly_name: "Couch Lamp"
          icon: mdi:lamp
